### ISSUE TITLE
Sources of the pump'n'dump detector

### ISSUE THREAD

**Issue by dgellow** [SystemsLab-Sapienza/pump-and-dump-dataset#1]
Hi there. Your paper "Pump and Dumps in the Bitcoin Era: Real Time Detection of Cryptocurrency Market Manipulations" mentions a tool to detect pump'n'dump activity in 25seconds. Are sources available somewhere?

**Comment by Ansijax** [comment]
Hi @dgellow, unfortunately, there is no public version available online of our source code. However, in the paper, there are all the details to replicate our tool.

**Comment by dgellow** [comment]
Thanks
